apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-kafka
  template:
    metadata:
      labels:
        app: flask-kafka
    spec:
      containers:
        - name: flask-kafka
          image: kirtanp8/flask-kafka:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-kafka
spec:
  selector:
    app: flask-kafka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
